name: 'admin: register org'
on:
  push:
    branches:
      - actions-permissions
jobs:
  register-org:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: config git
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email 'git@prevision.cloud'
          git config --global user.name 'PrevisionApp'
