name: Manage Reviewers
run-name: 'Manage Reviewers: ${{ github.event_name }}.${{ github.event.action }}'
on:
  pull_request:
    types:
    - opened
    - synchronize
    - ready_for_review
  pull_request_review:
jobs:
  debugger:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: |
          gh api /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews | jq '.'
      - run: |
          echo '${{ toJSON(github.event) }}' >> event.json

          echo '>>>>>> requested users:'
          jq '.pull_request.requested_reviewers' event.json
          echo '>>>>>> requested teams:'
          jq '.pull_request.requested_teams' event.json
          echo '>>>>>> new review:'
          jq '.review' event.json
          
