name: Manage Reviewers
run-name: 'Manage Reviewers: ${{ github.event_name }}.${{ github.event.action }}'
on:
  pull_request:
    types:
    - opened 
    - synchronize
    - ready_for_review
  pull_request_review:
jobs:
  debugger:
    runs-on: ubuntu-latest
    steps:
      - name: Parse pull request
        uses: actions/github-script@v7
        with:
          script: |
            // load event
            const pull_request = JSON.parse(`${{ toJSON(github.event.pull_request) }}`);
            
            console.debug(pull_request.requested_reviewers);
            console.debug(pull_request.requested_teams);

            // read pull reviews
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: '${{ github.event.pull_request.number }}'
            });

            if (200 == reviews.status) {
              let approved = [];
              for (let review of reviews.data) {
                if ('APPROVED' == review.status) {
                  approved.push(review);
                }
              }
              console.debug(approved);
            } else {
              throw 'Failed to read reviews on Pull Request #${{ github.event.pull_request.number }}';
            }
